apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
  namespace: app
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
      tier: web
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: hello-app
        image: europe-west1-docker.pkg.dev/pod-x-sarjan-purohit/jenkins/hello-app:{batman}
        ports:
        - containerPort: 8080
        # resources:
        #   requests:
        #     cpu: 200m
        #
