apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: jenkins-default-agent
spec:
  serviceAccountName: cd-jenkins
  containers:
  - name: jnlp
    image: europe-west1-docker.pkg.dev/pod-x-sarjan-purohit/jenkins-slave/jenkins-slave:latest
    securityContext:
      runAsUser: 0
    imagePullPolicy: Always
    volumeMounts:
    - name: docker-socket
      mountPath: /var/run/docker.sock
    - name: gcloud-config
      mountPath: /root/.config
  volumes:
  - name: docker-socket
    hostPath:
      path: /var/run/docker.sock
      type: Socket
  - name: gcloud-config
    emptyDir: {}
